### ISSUE TITLE
Choose the dataset

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/dsci-522-group14#2]
From the meeting on 19/11/20:
We decided to work on a predictive statistical question. We still need to finalize on a dataset to use

**Comment by vigneshRajakumar** [comment]
Data:
https://github.com/fivethirtyeight/data/tree/master/steak-survey

We have a bunch of binary and categorical variables that we can use to predict how someone would like their steak.

Pros:
- Simple question
- Data is already in csv

Cons:
- The data set is small: ~550 rows.

**Comment by yuyanguo** [comment]
This is a dataset about  predicting is if the client will subscribe (yes/no) a term deposit.(Bank product)

Pros: 

- Having 20 features, including binary, numerical and categorical

- The data set is large enough

- The problem is a binary classification problem. We learn a lot about it so far.

Cons:
- CSV is under a zip file. Hard to download.

Link: https://archive.ics.uci.edu/ml/datasets/Bank+Marketing

**Comment by jianructose** [comment]
What I found: https://datahub.io/core/covid-19#resource-worldwide-aggregate

Dataset about COVID-19 worldwide or us up-to-now version, but I haven't come up with a question yet.

PROS: 
- Big sample size.
- csv or json

CONS:
- not sure how to generate a ml question (it seems more proper for time-series)

**Comment by camharris22** [comment]
I'll go with this dataset: https://archive.ics.uci.edu/ml/datasets/Wine+Quality

Dataset is about wine quality using different wine features like acidity, sugar, pH, etc. 

PROS:
* ~5000 observations and 11 features
* CSV download available

CONS:
* Multi-class classification (score from 0-10)
* Dataset is split in two for red and white wines

> Picking this
